# =============================================================================
# Taskfile for AKS Vault Stack
# Task automation for deploying and managing Vault on Azure AKS
#
# Usage:
#   Deployment workflow:
#     task infra        - Deploy AKS infrastructure (aliases: aks, k8s)
#     task up           - Deploy Vault to AKS
#     task port-forward - Start port forwarding to Vault
#     task init         - Initialise Vault
#     task unseal       - Unseal Vault
#     task vso          - Deploy Vault Secrets Operator (optional)
#
#   Cleanup:
#     task rm      - Clear cluster (VSO, Vault) - keeps AKS running
#     task nuke    - Destroy ALL infrastructure including AKS
# =============================================================================

version: '3'

vars:
  NAMESPACE: vault
  VAULT_POD: vault-0

tasks:
  # ---------------------------------------------------------------------------
  # Main Deployment Tasks
  # ---------------------------------------------------------------------------

  infra:
    desc: Deploy core infrastructure (AKS + PostgreSQL)
    aliases: [core]
    cmds:
      - ./scripts/10_deploy_core_infra.sh

  vault:
    aliases: [up]
    desc: Deploy Vault to AKS cluster
    cmds:
      - ./scripts/20_deploy_vault.sh
      
  port-forward:
    aliases: [fwd, forward]
    desc: Start port forwarding to Vault
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/30_port_forwarding.sh

  init:
    desc: Initialise Vault, unseal, and set up port forwarding
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/40_vault_init.sh

  unseal:
    desc: Unseal Vault and set up port forwarding (use after pod restarts)
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/50_vault_unseal.sh
      - NAMESPACE={{.NAMESPACE}} ./scripts/30_port_forwarding.sh

  vso:
    desc: Deploy Vault Secrets Operator (run after Vault is initialised)
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/vso/00_deploy_vso.sh

  postgres-dynamic:
    desc: Configure Vault for dynamic PostgreSQL credentials (run after VSO is deployed)
    aliases: [dynamic]
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/vso/01_configure_postgres_dynamic.sh

  # ---------------------------------------------------------------------------
  # Utility Tasks
  # ---------------------------------------------------------------------------

  status:
    desc: Check status of Vault pods
    cmds:
      - kubectl get pods -n {{.NAMESPACE}} -l app.kubernetes.io/name=vault
      - echo ""
      - echo "Checking Vault status..."
      - kubectl exec -n {{.NAMESPACE}} {{.VAULT_POD}} -- vault status || true

  logs:
    desc: View Vault logs
    cmds:
      - kubectl logs -n {{.NAMESPACE}} -l app.kubernetes.io/name=vault --tail=100 -f

  vso-logs:
    desc: View VSO logs
    cmds:
      - kubectl logs -n {{.NAMESPACE}} -l app.kubernetes.io/name=vault-secrets-operator --tail=100 -f

  # ---------------------------------------------------------------------------
  # Kubernetes Operations
  # ---------------------------------------------------------------------------

  k9s:
    desc: Open k9s for the Vault namespace
    cmds:
      - k9s -n {{.NAMESPACE}}

  pods:
    desc: List all pods in Vault namespace
    cmds:
      - kubectl get pods -n {{.NAMESPACE}}

  services:
    desc: List all services in Vault namespace
    cmds:
      - kubectl get svc -n {{.NAMESPACE}}

  # ---------------------------------------------------------------------------
  # Cleanup Tasks
  # ---------------------------------------------------------------------------

  rm:
    desc: Clear cluster resources (removes VSO and Vault, keeps AKS running)
    aliases: [clean]
    cmds:
      - ./scripts/tools/clear_aks_cluster.sh

  nuke:
    desc: Destroy ALL infrastructure including AKS
    aliases: [destroy, wipeout, purge]
    cmds:
      - ./scripts/tools/nuke.sh

  # ---------------------------------------------------------------------------
  # Information Tasks
  # ---------------------------------------------------------------------------

  info:
    desc: Display connection information and dynamic credentials
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/tools/info.sh

  help:
    desc: Show available tasks
    cmds:
      - task --list
