# =============================================================================
# Taskfile for AKS Vault Stack
# Task automation for deploying and managing Vault on Azure AKS
#
# Usage:
#   Full deployment workflow (run tasks in order):
#     task login        - Authenticate to Azure
#     task infra        - Deploy AKS infrastructure (aliases: core)
#     task up           - Deploy Vault to AKS (aliases: vault)
#     task init         - Initialise Vault + port-forward
#     task audit        - Configure Vault audit devices
#     task vso          - Deploy Vault Secrets Operator
#     task workload1    - Deploy workload 1 (PostgreSQL + JWT auth)
#
#   Utility tasks:
#     task port-forward - Start port forwarding to Vault
#     task unseal       - Unseal Vault + port-forward (use after pod restarts)
#     task info         - Display connection information and credentials
#     task audit-logs   - Export main audit logs as raw JSON to data/audit-logs.json
#     task db-logs      - Query database credential audit logs and export to data/db-logs.json (default: last 10 records)
#     task db-logs limit=20 - Query database audit logs with custom limit (last 20 records per section)
#     task revoke path=<lease_path> - Revoke a database credential lease
#     task delete-k8s-secret - Delete the Kubernetes secret created by VSO
#     task psql username=<user> password=<pass> - Connect to PostgreSQL
#
#   Cleanup:
#     task rm           - Clear cluster (VSO, Vault) - keeps AKS running
#     task nuke         - Destroy ALL infrastructure including AKS
# =============================================================================

version: '3'

vars:
  NAMESPACE: vault
  VAULT_POD: vault-0

tasks:
  # ---------------------------------------------------------------------------
  # Azure Authentication
  # ---------------------------------------------------------------------------

  azure-login:
    desc: Login to Azure with tenant
    aliases: [login]
    cmds:
      - az login --tenant 237fbc04-c52a-458b-af97-eaf7157c0cd4

  # ---------------------------------------------------------------------------
  # Main Deployment Tasks
  # ---------------------------------------------------------------------------

  infra:
    desc: Deploy core infrastructure (AKS + PostgreSQL)
    aliases: [core]
    cmds:
      - ./scripts/10_deploy_core_infra.sh

  vault:
    desc: Deploy Vault to AKS cluster
    aliases: [up]
    cmds:
      - ./scripts/20_deploy_vault.sh
      
  port-forward:
    desc: Start port forwarding to Vault
    aliases: [fwd, forward]
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/30_port_forwarding.sh

  init:
    desc: Initialise Vault, unseal, and set up port forwarding
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/40_vault_init.sh
      - NAMESPACE={{.NAMESPACE}} ./scripts/30_port_forwarding.sh

  unseal:
    desc: Unseal Vault and set up port forwarding (use after pod restarts)
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/50_vault_unseal.sh
      - NAMESPACE={{.NAMESPACE}} ./scripts/30_port_forwarding.sh

  vso:
    desc: Deploy Vault Secrets Operator (run after Vault is initialised)
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/vso/00_deploy_vso.sh

  workload1:
    desc: Deploy workload 1
    aliases: [wkd1, wkd]
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/workload-1/01_configure_jwt_auth.sh

  audit:
    desc: Configure Vault audit devices (run after Vault is initialised and unsealed)
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/audit-devices/01_configure_audit.sh

  # ---------------------------------------------------------------------------
  # Utility Tasks
  # ---------------------------------------------------------------------------

  status:
    desc: Check status of Vault pods
    cmds:
      - kubectl get pods -n {{.NAMESPACE}} -l app.kubernetes.io/name=vault
      - echo ""
      - echo "Checking Vault status..."
      - kubectl exec -n {{.NAMESPACE}} {{.VAULT_POD}} -- vault status || true

  logs:
    desc: View Vault logs
    cmds:
      - kubectl logs -n {{.NAMESPACE}} -l app.kubernetes.io/name=vault --tail=100 -f

  vso-logs:
    desc: View VSO logs
    cmds:
      - kubectl logs -n {{.NAMESPACE}} -l app.kubernetes.io/name=vault-secrets-operator --tail=100 -f
  
  revoke:
    desc: Revoke a database credential lease
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/tools/revoke_lease_db.sh "{{.path}}"

  # ---------------------------------------------------------------------------
  # Kubernetes Operations
  # ---------------------------------------------------------------------------

  pods:
    desc: List all pods in Vault namespace
    cmds:
      - kubectl get pods -n {{.NAMESPACE}}

  services:
    desc: List all services in Vault namespace
    cmds:
      - kubectl get svc -n {{.NAMESPACE}}

  delete-k8s-secret:
    desc: Delete the Kubernetes secret created by Vault Secrets Operator
    cmds:
      - kubectl delete secret postgres-dynamic-creds-wrkld1 -n {{.NAMESPACE}} --ignore-not-found

  # ---------------------------------------------------------------------------
  # Cleanup Tasks
  # ---------------------------------------------------------------------------

  rm:
    desc: Clear cluster resources (removes VSO and Vault, keeps AKS running)
    aliases: [clean]
    cmds:
      - ./scripts/tools/clear_aks_cluster.sh

  nuke:
    desc: Destroy ALL infrastructure including AKS
    aliases: [destroy, wipeout, purge, kill]
    cmds:
      - ./scripts/tools/nuke.sh

  # ---------------------------------------------------------------------------
  # Information Tasks
  # ---------------------------------------------------------------------------

  info:
    desc: Display connection information and dynamic credentials
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/tools/info.sh

  audit-logs:
    desc: Export main Vault audit logs as raw JSON to data/audit-logs.json
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/tools/audit-logs-data.sh

  db-logs:
    desc: Query database credential audit logs and export to data/db-logs.json (limit={{.limit | default "10"}})
    aliases: [logs-db, database-logs]
    cmds:
      - NAMESPACE={{.NAMESPACE}} LIMIT={{.limit | default "10"}} ./scripts/tools/db-logs-data.sh


  # ---------------------------------------------------------------------------
  # PostgreSQL Connection
  # ---------------------------------------------------------------------------

  psql:
    desc: Connect to PostgreSQL database
    cmds:
      - ./scripts/tools/psql_connect.sh "{{.username}}" "{{.password}}"

  help:
    desc: Show available tasks
    cmds:
      - task --list
