#!/bin/bash

# =============================================================================
# Deploy Core Infrastructure
# This script deploys AKS cluster and PostgreSQL database
# =============================================================================

set -e

# Source centralised colour configuration
source "$(dirname "$0")/lib/colors.sh"

# -----------------------------------------------------------------------------
# Load environment variables from .env file
# Required variables: ARM_SUBSCRIPTION_ID, ARM_TENANT_ID, POSTGRES_ADMIN_PASSWORD
# -----------------------------------------------------------------------------
if [ -f "$(dirname "$0")/../.env" ]; then
  echo -e "${BLUE}Loading environment variables from .env file...${NC}"
  set -a  # Automatically export all variables
  source "$(dirname "$0")/../.env"
  set +a  # Disable automatic export
  echo -e "${GREEN}✓ Environment variables loaded${NC}"
  echo ""
else
  echo -e "${RED}Error: .env file not found${NC}"
  echo "Please create a .env file with required variables:"
  echo "  ARM_SUBSCRIPTION_ID, ARM_TENANT_ID, POSTGRES_ADMIN_PASSWORD"
  exit 1
fi

# Validate required environment variables
if [ -z "$ARM_SUBSCRIPTION_ID" ] || [ -z "$ARM_TENANT_ID" ]; then
  echo -e "${RED}Error: Required Azure credentials not set in .env${NC}"
  echo "Please set ARM_SUBSCRIPTION_ID and ARM_TENANT_ID in .env file"
  exit 1
fi

# Check for PostgreSQL admin password
if [ -z "$POSTGRES_ADMIN_PASSWORD" ]; then
  echo -e "${RED}Error: POSTGRES_ADMIN_PASSWORD not set in .env${NC}"
  echo "Please set POSTGRES_ADMIN_PASSWORD in .env file"
  exit 1
fi

# Export Terraform variables
export TF_VAR_subscription_id="$ARM_SUBSCRIPTION_ID"
export TF_VAR_tenant_id="$ARM_TENANT_ID"
export TF_VAR_postgres_admin_password="$POSTGRES_ADMIN_PASSWORD"

echo -e "${BLUE}=== Deploying Core Infrastructure ===${NC}"
echo ""

# -----------------------------------------------------------------------------
# Deploy Core Infrastructure (AKS + PostgreSQL)
# -----------------------------------------------------------------------------
echo -e "${BLUE}Deploying Core Infrastructure (AKS + PostgreSQL)${NC}"
cd "$(dirname "$0")/../terraform/core-infra"

# Initialise Terraform
echo -e "${BLUE}Initialising Terraform (Core Infrastructure)...${NC}"
terraform init -upgrade

# Apply Terraform configuration
echo -e "${BLUE}Applying Terraform configuration (AKS + PostgreSQL)...${NC}"
terraform apply -auto-approve

echo ""
echo -e "${GREEN}✓ Core Infrastructure deployed successfully${NC}"
echo ""

# Capture Terraform outputs
echo -e "${BLUE}Capturing infrastructure outputs...${NC}"
RESOURCE_GROUP=$(terraform output -raw resource_group_name)
CLUSTER_NAME=$(terraform output -raw aks_cluster_name)
POSTGRES_SERVER_FQDN=$(terraform output -raw postgres_server_fqdn)
POSTGRES_DATABASE=$(terraform output -raw postgres_database_name)
POSTGRES_ADMIN_USER=$(terraform output -raw postgres_admin_username)
OIDC_ISSUER_URL=$(terraform output -raw aks_oidc_issuer_url)

# Update .env file with infrastructure outputs
echo -e "${BLUE}Updating .env with infrastructure details...${NC}"
cd "$(dirname "$0")/.."

# Create or update .env file with infrastructure variables
if [ ! -f .env ]; then
  cat > .env <<EOF
# -----------------------------------------------------------------------------
# Azure Infrastructure Outputs (auto-generated by 10_deploy_core_infra.sh)
# -----------------------------------------------------------------------------
export AKS_RESOURCE_GROUP=$RESOURCE_GROUP
export AKS_CLUSTER_NAME=$CLUSTER_NAME
export POSTGRES_SERVER_FQDN=$POSTGRES_SERVER_FQDN
export POSTGRES_DATABASE=$POSTGRES_DATABASE
export POSTGRES_ADMIN_USER=$POSTGRES_ADMIN_USER
export AKS_OIDC_ISSUER_URL=$OIDC_ISSUER_URL
EOF
else
  # Update or add infrastructure variables
  for VAR in "AKS_RESOURCE_GROUP=$RESOURCE_GROUP" "AKS_CLUSTER_NAME=$CLUSTER_NAME" \
             "POSTGRES_SERVER_FQDN=$POSTGRES_SERVER_FQDN" "POSTGRES_DATABASE=$POSTGRES_DATABASE" \
             "POSTGRES_ADMIN_USER=$POSTGRES_ADMIN_USER" "AKS_OIDC_ISSUER_URL=$OIDC_ISSUER_URL"; do
    VAR_NAME=$(echo "$VAR" | cut -d= -f1)
    VAR_VALUE=$(echo "$VAR" | cut -d= -f2-)
    if grep -q "^export $VAR_NAME=" .env; then
      sed -i.bak "s|^export $VAR_NAME=.*|export $VAR_NAME=$VAR_VALUE|" .env
    elif grep -q "^$VAR_NAME=" .env; then
      sed -i.bak "s|^$VAR_NAME=.*|export $VAR_NAME=$VAR_VALUE|" .env
    else
      echo "export $VAR_NAME=$VAR_VALUE" >> .env
    fi
  done
  rm -f .env.bak
fi

echo -e "${GREEN}✓ Infrastructure details saved to .env${NC}"
echo ""

# Get AKS credentials
echo -e "${BLUE}Configuring kubectl for AKS...${NC}"
az aks get-credentials --resource-group "$RESOURCE_GROUP" --name "$CLUSTER_NAME" --admin --overwrite-existing

echo -e "${GREEN}✓ kubectl configured for AKS cluster${NC}"
echo ""

# Display infrastructure information
echo -e "${BLUE}PostgreSQL Database Information:${NC}"
echo "  Server: $POSTGRES_SERVER_FQDN"
echo "  Database: $POSTGRES_DATABASE"
echo ""

echo ""
echo -e "${GREEN}=== Core Infrastructure Deployment Complete! ===${NC}"
echo ""
